name: laundry_link
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.3
  responsive_framework: ^1.4.0
  flutter_screenutil: ^5.9.3
  another_flutter_splash_screen: ^1.2.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  dio: ^5.6.0

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/icons/
